# Generated by Django 5.1.3 on 2024-12-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_remove_activity_exercise'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
            preserve_default=False,
        ),
    ]
