# Generated by Django 5.1.3 on 2024-12-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_activity_exercise'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
