# Generated by Django 5.1.3 on 2024-12-12 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_alter_activity_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_per_minute',
            field=models.IntegerField(blank=True, default=0, help_text='Kcal', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='exercise_duration',
            field=models.IntegerField(default=1, help_text='Minute', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
