# Generated by Django 5.1.3 on 2024-12-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_alter_activity_calories_per_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='exercise',
        ),
    ]
