# Generated by Django 5.1.3 on 2024-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_activity_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_per_minute',
            field=models.FloatField(blank=True, default=0.0, help_text='Kcal', null=True),
        ),
    ]
