# Generated by Django 5.1.3 on 2024-12-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_alter_activity_calories_per_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='exercise',
        ),
    ]
