# Generated by Django 5.1.3 on 2024-12-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0024_activity_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
