# Generated by Django 5.1.3 on 2024-12-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0025_delete_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_per_minute',
            field=models.IntegerField(blank=True, default=0, help_text='Kcal', null=True),
        ),
    ]
